### PR TITLE
Remove BlockProperties

### PR DESCRIPTION
**Pull request by SoniEx2**
Split the monolithic BlockProperties class into multiple smaller classes.

### CODE REVIEW

**Comment by SoniEx2** [comment]
@calclavia may I have write access yet?

**Comment by RX14** [comment]
@SoniEx2 no, and asking for it will never further your case.

**Comment by calclavia** [comment]
Should we merge this?

**Comment by SoniEx2** [comment]
I guess I could clean it up a bit still, there are a few rough spots here and there...

**Comment by RX14** [comment]
I can't remember the advantages or disadvantages or why this was done this way originally.

**Comment by SoniEx2** [comment]
@RX14 It was done this way because it mimics MC better, you can see that quite clearly from the code.

**Comment by ExE-Boss** [comment]
It would make it easier to add new properties.
I would also recommend that all the classes in the BlockProperty interface also implement BlockProperty.

**Comment by SoniEx2** [comment]
How should `Replaceable` be done? It would be the first singleton `Component` in the whole codebase, I think.

How should `shouldDisplacePlacement` be done? I'm not sure if I can do it like `Replaceable` because `shouldDisplacePlacement` is true by default, while `Replaceable` is false by default (i.e. adding `Replaceable` makes a block replaceable, while for `shouldDisplacePlacement` it'd have to be the opposite?)

**Comment by SoniEx2** [comment]
@RX14 please review my PR, lexmanos-sama.

**Comment by RX14** [comment]
name calling certainly doesn't make me want to merge your PR.

**Comment by SoniEx2** [comment]
@RX14 please review my pull request, RX14-sama

**Comment by SoniEx2** [comment]
Kinda sucks that I can't make more PRs without this getting merged first :/

**Comment by RX14** [comment]
@SoniEx2 Yes you can, you can `git checkout -b` from any branch...

**Comment by SoniEx2** [comment]
@RX14 I can develop, sure, but not make PRs

**Comment by RX14** [comment]
@SoniEx2 you have a branch... which you can push to git... and make a PR? I don't see the problem. Sure they'll c0ontain commits from unmerged PRs but thats what rebase is for.

**Comment by RX14** [comment]
I assume you've tested this change in MC. If it works i'll merge.

**Comment by SoniEx2** [comment]
I have not.

**Comment by ExE-Boss** [comment]
I have tested it on all versions (1.7, 1.8 and 1.11) and I can confirm that it does work.

**Comment by RX14** [comment]
Rebased and merged on master.

**Pull request closed without merging**
