### PR TITLE
Migrate dependencies to the Java Library Gradle plugin

### PR DESCRIPTION
**Pull request by ExE-Boss**
This migrates the dependencies of NOVA-Core to use the [Java Library Plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html) (see #313).

### CODE REVIEW

**Comment by ExE-Boss** [comment]
It’s because `java-library` requires Gradle 3+, but ForgeGradle 1.2 is incompatible with Gradle 4+.

**Comment by RX14** [comment]
Would be nice if you had time to work on the actual code instead of just mess with gradle :)

**Comment by ExE-Boss** [comment]
I have been working on the [`refactor/inventory`](https://github.com/NOVA-Team/NOVA-Core/tree/refactor/inventory) branch, but that required this, NOVA-Team/NOVA-Gradle#16 and NOVA-Team/NOVA-Gradle#17 to be merged because of the ForgeGradle issues.

**Comment by RX14** [comment]
Oh cool, nice to know.

**Pull request merged**
