### PR TITLE
Nuke commands from core

### LINKED ISSUE #220: Split commands off of core
Commands should be a separate plugin. Mostly because the current command system is total shit and commands are rarely used.

### PR DESCRIPTION
**Pull request by SoniEx2**
The command API was shit anyway. This does away with it.

We should redesign the API and have it as a separate plugin.

Closes #220

### CODE REVIEW

**Comment by calclavia** [comment]
Can you create a new repo and move the existing command system to that repo? The command system could be improved later on.

**Comment by SoniEx2** [comment]
The command system needs to be nuked from orbit and rewritten from scratch.

All methods in `Args` need to be renamed, perhaps also extracted to a separate `Arg` class, etc. It's easier to nuke the whole thing and start over than try to refactor until it looks nice.

**Comment by SoniEx2** [comment]
Also, no, I can't create NOVA-Team repos.

**Comment by calclavia** [comment]
@SoniEx2 Alright. Put in an issue to write a better command system.

**Pull request merged**
