### PR TITLE
Command Features

### PR DESCRIPTION
**Pull request by calclavia**

### CODE REVIEW

**Comment by calclavia** [comment]
If @Kubuxu @RX14 approves of this simple command API, I'll merge. Any suggestions/opinions/feedback?

**Comment by Kubuxu** [comment]
What if alias is conflicting with other commend ID?

**Comment by calclavia** [comment]
@Kubuxu Good point... then how should we do alias?

**Comment by Kubuxu** [comment]
If there is ID - alias conflict ID wins. If there is alias-alias conflict this alias is registered (take into account more than one conflict). ID-ID conflict error out.

**Comment by calclavia** [comment]
@Kubuxu Agreed

**Comment by Victorious3** [comment]
I think it needs proper args, not in the form of an array but in an object that can handle validation and conversions.

**Comment by AEnterprise** [comment]
could a framework for autocompletion of pars also be added?

**Comment by RX14** [comment]
Why not add a command parser in with subcommands etc, and make that autocomplete too.

**Comment by AEnterprise** [comment]
that's probably even better

**Comment by Caellian** [comment]
@Victorious3 Can you clarify proper args. You do know that console uses text input. I think String[] is the best way to handle it and let the mod dev do what he/she wants.

**Comment by Caellian** [comment]
I mean, you will always know what input your command will take and autocomplete is handled by you.
The best you could do is add a argument parser like [this](https://github.com/Caellian/CaellianCore/blob/master/src/main/java/com/caellian/core/ArgumentHelper.java) (trough I think mine is a overcomplicated).

**Comment by Victorious3** [comment]
@Caellian No. You get an object where you can do something like:
```
int i = args.checkint(1);
```
Its not slower than doing the validation yourself, and it is a lot more convenient.

**Comment by Caellian** [comment]
So args would be a custom object with checkType methods? That's a good idea I guess.

**Comment by Victorious3** [comment]
@RX14 Sub-commands are basically just this:
```java
switch(arg.checkstring(0) {
    case "subcommand1" : ...
    case "subcommand2" : ...
}
```
I don't think you need an extra framework for that.

**Comment by Victorious3** [comment]
@Caellian Random thing, style related:
Requiring the user to return a list, collection, map... Is something I'd like to avoid. I find it a lot more convenient if you get one passed as argument that you can modify.

**Comment by Caellian** [comment]
@Victorious3 I agree with you, when executing commands users should be able to call just args.parseIntAt(pos) and get that argument parsed and prepeared, if it doesn't exist or can't be parsed correctly, it should return null.

Also, with tab completion, users should probably return an Object[] or null in case multiple results are possible.

**Comment by RX14** [comment]
@Victorious3 it's so much more than just subcommands. Optional parameters and different command formats too. The framework however will have to be built on top of a lower abstraction, and this can be it. Another useful command on the args object would be getting the string from argument x to the end of the line. What about quotes parsing? Do we act like bash or just split on space?

**Comment by Victorious3** [comment]
@RX14 Optional parameters? Easy, `args.optint(0, default)`
I wouldn't overcomplicate it. Split on spaces and '"', there is a nice regex around. I don't think that fancy stuff like flags is really needed, after all most of the commands are meant to be simple, this is just a game and not a command line utility.

**Comment by RX14** [comment]
@Victorious3 whether you think we need a more high level framework is irrelevant right now, we need to agree on the base abstraction, and I think we have.

**Comment by calclavia** [comment]
@Victorious3 Make a PR if you want to.

**Pull request merged**
