### PR TITLE
Minecraft 1.11.2 wrappers

### PR DESCRIPTION
**Pull request by ExE-Boss**
I’ve begun work on wrappers for Minecraft 1.11.

### Depends on:
- ~~#300~~ (merged)
- #291
- ~~#290~~ (merged)

### To do list:
- [ ] Fix `FWSmartItemModel`'s `ItemCameraTransforms`
- [ ] Fix `BWModel.render`
- [ ] Switch to `ICapabilityProvider` where appropriate. Thanks @shadowfacts for pointing that out at https://github.com/MinecraftForge/MinecraftForge/pull/3599#issuecomment-270259637. (Depends on #261)
    - [x] Create `FWCapabilityProvider`
    - [x] Use Forge Capabilities to make NOVA items persistent (Thanks @LexManos https://github.com/MinecraftForge/MinecraftForge/issues/3782#issuecomment-286231964)
    - [ ] Implement capability wrappers
- [ ] `MCParticleTransform.rotation` (low priority, will probably be made obsolete by #281)

### Completed:
- [x] Fix compile errors
- [x] Make Minecraft 1.11 run
- [x] Test with NOVA-Team/NOVA-Example#31
- [x] Create framework for NOVA-Team/NOVA-Energy#2
- [x] ~~Squash all commits~~ Backed out because NOVA has moved to using merge commits
- [x] Upgrade to 1.11.2 when Forge releases a stable 1.11.2 release
- [x] Fix block textures
- [x] Add normals to `FWSmartModel.vertexToInts`
- [x] Fix `TileEntityTransformer`
- [x] Fix build script fat jar reobfuscation (the normal jar obfuscates properly, low priority)

---

Moved from: #231
P.S.: I will do my best to not let NOVA die just yet, I just hope that life won’t get in the way of that.

### CODE REVIEW

**Comment by RX14** [comment]
Ignore coverage for this PR because it's a MC wrapper. I'll merge it regardless.

**Comment by calclavia** [comment]
@RX14 Should we add @ExE-Boss as a contributor? He's made a decent amount of PRs

**Comment by RX14** [comment]
@calclavia He is, I've made it so that all commits to the master branch need to be reviewed though.

**Comment by loordgek** [comment]
@ExE-Boss do you know that MC itemstack cannot be null??
do you know how the Capability stuff works?(it is realy cool)

**Comment by ExE-Boss** [comment]
@loordgek I am aware of both.

**Pull request merged**
