### PR TITLE
Minecraft 1.11 wrappers

### PR DESCRIPTION
**Pull request by ExE-Boss**
PR has been moved to: #234

---

I’ve begun work on wrappers for Minecraft 1.11.
Depends on:
- #226 (merged) and #229, as they both affect wrappers directly.
- #232, because this PR contains files added by that PR so that I could also work on NOVA-Team/NOVA-Worldgen#1.

To do list:
- [ ] Fix block textures
- [ ] Fix `TileEntityTransformer`
- [ ] Switch to `ICapabilityProvider` where appropriate. Thanks @shadowfacts for pointing that out at [MinecraftForge/MinecraftForge#3599](https://github.com/MinecraftForge/MinecraftForge/pull/3599#issuecomment-270259637).
- [ ] `BWModel.render`: calculate brightness correctly (possibly works, but needs testing)
- [ ] `MCParticleTransform.rotation` (low priority)
- [ ] Fix build script fat jar reobfuscation (the normal jar obfuscates properly, low priority)

Completed:
- [x] Fix compile errors
- [x] Make Minecraft 1.11 run
- [x] Test with NOVA-Team/NOVA-Example#31
- [x] Create framework for NOVA-Team/NOVA-Energy#2

---

P.S.: I will do my best to not let NOVA die just yet, I just hope that life won’t get in the way of that.

### CODE REVIEW

**Comment by liach** [comment]
https://github.com/NOVA-Team/NOVA-Core#nova-is-no-longer-maintained

**Comment by ExE-Boss** [comment]
@liach Yes, I know. But that won’t stop me from making the Minecraft 1.11 wrappers anyway.

**Comment by calclavia** [comment]
@ExE-Boss If you manage to get it working, I'll be happy to merge stuff

**Comment by ExE-Boss** [comment]
One question though, should the package be `nova.core.wrapper.mc.forge.v111` or `nova.core.wrapper.mc.forge.v1_11`?
I vote for the second option, as it’s clearer than the first and won’t be as likely to conflict.

**Comment by RX14** [comment]
@ExE-Boss Second option

**Comment by SoniEx2** [comment]
I love you @ExE-Boss

**Comment by ExE-Boss** [comment]
Debugging the TileEntityTransformer class will be very difficult for me, as this is my first time dealing with Java bytecode directly and ForgeGradle has no :debugClient task, without which breakpoints can’t be used.

But from what I can gather, it seems to have something to do with the changes it does to the TileEntity class causing NullPointerException to be thrown inside the ObjectWeb ASM library.

**Comment by RX14** [comment]
@ExE-Boss can you come on IRC?

**Comment by ExE-Boss** [comment]
Wouldn’t it be easier to use Discord?
I have already set it up (with permission from shadowfacts).

**Comment by RX14** [comment]
@ExE-Boss set what up where?

**Comment by ExE-Boss** [comment]
https://discord.gg/wMuv2rM

**Comment by SoniEx2** [comment]
Relevant xkcd: http://xkcd.com/1782/

**Comment by ExE-Boss** [comment]
PR has been moved to: #234

**Pull request closed without merging**
