### PR TITLE
Here goes the configuration

### PR DESCRIPTION
**Pull request by anti344**
Well, looks good for me, all tests passing, code looks for good 8/10 style points(if not look at reflection stuff).

### CODE REVIEW

**Comment by RX14** [comment]
Looks good to me apart from the compilation failure. 

Maybe nova.core.config would be better than nova.core.util.config

Would also love some docs for this! Just send in a  PR.

**Comment by RX14** [comment]
To give you a hint, this looks to me as if you are using an internal API which is not in the openjdk.

**Comment by anti344** [comment]
Lol, this small rearrange comment may fix this. Removed wrong (and unused) import that caused the problem.

**Comment by RX14** [comment]
Looks like your tests failed.

**Comment by anti344** [comment]
Yup, just saw

**Comment by anti344** [comment]
Weird
image

**Comment by RX14** [comment]
Try debugging using gradle test. And who are you in IRC again?

**Comment by RX14** [comment]
Also keep in mind that with gradle each test is run in a separate JVM. This means that some tests working on idea break because of inter-test dependencies

**Comment by anti344** [comment]
I'll squeze this commits later, this one is just to run Travis again

**Comment by anti344** [comment]
Finally

**Comment by RX14** [comment]
Noice

**Pull request merged**
