### PR TITLE
Integrated new rendering pipeline

### LINKED ISSUE #104: Ability to get render an existing object...
NOVA needs the ability to get the renderer for an existing object (item, block, entity, etc.).

This would be used in order to do things like Buildcraft pipes, or translocator's crafting grid.  I think beyond being able to get item/block renderers, we need to be able to get entities as well.  It would allow us to do things like render a creature in a jar, or any number of creative things.

In addition, I think there may be some issues with making this work well the way Nova handles things.  Specifically, since Nova doesn't use meta-data itself, we need a way to pass data to the renderer that we acquire so that it will render the object using said object correctly.  As an example, you may want to render a container full of liquid.

### PR DESCRIPTION
**Pull request by calclavia**
Replaced the use of StaticBlockRenderer etc. "Special renderers" with a more modular approach. Using RenderStream along with transmutes to essentially "build" a model render function using builder patterns.

- [x] Hierarchical TreeNode implementation
- [x] Rendering pipeline
- [ ] Backward Rendering
- [ ] Clean up render components, removing redundant ItemRenderer

New Block Rendering Pattern
```
	add(new StaticRenderer(this)
		.setOnRender(
			RenderStream.of(new BlockRenderer(this))
				.withTexture(CoreContent.textureCreativeBuilder)
				.build()
		)
	)
```
Suggestions are welcome.

### CODE REVIEW

**Comment by calclavia** [comment]
Question @Kubuxu :
Instead of passing Model in renderers, maybe we should pass RenderStream instead? That way, rendering can hold more data that just its model. For example, ItemRendering may way to know about "the current state of item rendering". Is the item being rendered while held up? View in 3rd person mode?

**Comment by Kubuxu** [comment]
This could be useful. I am bad at taking design decisions so you shouldn't as me about it but it seams useful.

**Comment by anti344** [comment]
There needs to be some king of 'defaults', because setting renderer for each block this way is kinda wonky.

block.add(new DefaultBlockRenderer(block)) fe

**Comment by calclavia** [comment]
@anti344 Yeah, i simplified it a bit more.

```
   add(new StaticRenderer(this)
        .setOnRender(
            new BlockRenderer(this)
                .withTexture(CoreContent.textureCreativeBuilder)
                .build()
        )
    )
```

**Comment by anti344** [comment]
```scala
trait MyBasicBlock extends Block{
  add(new StaticRenderer(this)(new BlockRenderer(this).withTexture(CoreContent.textureCreativeBuilder).build()))
}
```

Right? =P

**Comment by calclavia** [comment]
Yes.

**Comment by Caellian** [comment]
Is using traits a good idea considering everything is written in java???
I'm confused...

**Comment by gjgfuj** [comment]
Well, for your mod that's written in Scala.

**Comment by anti344** [comment]
@Caellian nah, i was lazy to write whole java class with whole constructor(at least without IDE)

**Comment by Caellian** [comment]
NOVA supports that?! Don't get me excited for nothing.

**Comment by anti344** [comment]
Well Scala compiles to JVM and NOVA-Scala has some scala utils..

**Pull request merged**
