### PR TITLE
Added getters to Game class.

### PR DESCRIPTION
**Pull request by halvors**
Added getters to Game class. This is not a breaking change, but as soon as the rest of the codebase has adapted to the Game.getInstance() instead of Game.instance etc, the methods that the getters is returning should be made private.

I don't know how you guys feel about all these getters, but as far as i know all other classes in NovaCore is using getters instead of directly accessing public variables.

And also, i skipped adding getters for the guiComponentFactory and guiFactory methods because of the TODO comment that says "Move somewhere else".

### CODE REVIEW

**Comment by calclavia** [comment]
Change to Game.instance(). Remove all the "get" terms as they are redundant and verbose.

**Comment by halvors** [comment]
Ok. Sure? I see that all the other classes in NoveCore have "get" terms, example ClientManager.getPlayer().

**Comment by halvors** [comment]
But if you insist i'll do it :-) Just thought that we should have a overall standard here, and as a said from my point of view, it seems like you guys already have a lot of "get" terms in the getters.

**Comment by Kubuxu** [comment]
Is this really needed change. Those variables are final so why getters?

**Comment by halvors** [comment]
@Kubuxu Yes they are, i just think that Game.getInstance() will look a lot more cleaner, and look a lot more like an API than Game.instance :)

**Comment by calclavia** [comment]
@Kubuxu I don't think it's not a needed change, it's just aesthetics. But @halvors, I would like all variables to not have "get" unless they have a setter. Look at RigidBody and tranform(). Most methods in NOVA don't use the get. It also looks bad on Scala.

**Comment by calclavia** [comment]
@Kubuxu I don't think it's not a needed change, it's just aesthetics. But @halvors, I would like all variables to not have "get" unless they have a setter. Look at RigidBody and tranform(). Most methods in NOVA don't use the get. It also looks bad on Scala.

**Comment by halvors** [comment]
@calclavia Ok. I get that it's bad scale practice, i'll change it and push a new commit :)

**Comment by halvors** [comment]
@calclavia In order for Game.instance to be set in the ModLoader class i added a Game.setInstance() method and thereby renamed Game.instance() to Game.getInstance() as you said since it has a setter and a getter.

**Comment by Victorious3** [comment]
I see no need for a getter on final fields.

**Comment by halvors** [comment]
@Victorious3 Should i remove them then and only keep Game.getInstance() and Game.setInstance()?

**Comment by Victorious3** [comment]
@halvors I'd use `instance()` and put an `@Deprecated` on the setter to indicate that it shouldn't be used by anything other than the wrapper. Could as well be called `inject(Game game)` or something like that.

**Comment by RX14** [comment]
well i'm partial to getInstance because mah groovy... Does scala have gorrvy-style mixins to existing classes? In groovy you can set a mixin class to automatically be applied from META-INF

**Comment by anti344** [comment]
Nope, Scala does not.

**Comment by RX14** [comment]
anyway... why do we need a getter/setter? why was the final field not good?

**Comment by Victorious3** [comment]
@RX14 instance is not a final field.

**Comment by RX14** [comment]
Why isn't it?

**Comment by halvors** [comment]
@RX14 Because the field is set in the ModLoader class.

**Comment by calclavia** [comment]
Ehh... I still feel getInstance() is too verbose. Everyone is going to use that method A LOT and the code looks much uglier with loads of "get()", especially with the amount of optionals we're using...

**Comment by anti344** [comment]
Just `Game.get()` ?

**Comment by Vexatos** [comment]
`Game.gimmehPls()` :dancer:

**Comment by calclavia** [comment]
@anti344 lol. The code will end up being: Game.get().thisManager().getBlockFactory().get().makeBlock().get()

**Comment by RX14** [comment]
it don't matter to me, when i write a mod in groovy I'll just add all the mixins i want :P

**Comment by halvors** [comment]
My intention was not to start a discussion here. Should we stick with Game.instance() and Game.inject(Game game).

**Comment by calclavia** [comment]
@halvors I agree with Game.instance() and Game.inject(Game game). Do that and I'll accept PR.

**Comment by halvors** [comment]
@calclavia Done ;)

**Comment by Victorious3** [comment]
Can you squash these? Contains a lot of commits that reverse itself.

**Comment by RX14** [comment]
I'll merge it

**Comment by RX14** [comment]
Merged

**Pull request closed without merging**
