### PR TITLE
Added basic command argument holder with type conversions

### PR DESCRIPTION
**Pull request by Victorious3**
Was mentioned here: #155
Since my workspace is currently a nuclear test site, I couldn't apply the changes to the wrapper yet.
I didn't implement range checks for the numeric types since it is a lot of repetitive code and I'm not sure if it is needed.

### CODE REVIEW

**Comment by RX14** [comment]
Make it possible to get a string from position X to the end of the line.

**Comment by RX14** [comment]
Also calling the getters `checkString` is strange.

**Comment by Victorious3** [comment]
@RX14 Consistency

**Comment by RX14** [comment]
How is that consistency? Just call it `getString(int position)`

**Comment by Victorious3** [comment]
Its consistency because all the other methods are named like that.

**Comment by RX14** [comment]
I mean rename all of the other ones to get too.. getString, getInt etc.

**Comment by RX14** [comment]
And why does optXXX have to be different, just overload with 2 args, that's how i've seen defaults done before.

**Comment by calclavia** [comment]
@Victorious3 Will wait for all tests to pass on wrapper as well before merge.

**Comment by calclavia** [comment]
@Victorious3 Merge ready?

**Pull request merged**
