### PR TITLE
Fix the build

### PR DESCRIPTION
**Pull request by SoniEx2**
This may fix the build.

### CODE REVIEW

**Comment by RX14** [comment]
Let me look into this.

**Comment by calclavia** [comment]
@SoniEx2 Build seems to be failing

**Comment by SoniEx2** [comment]
@calclavia Compilation works for main NOVA project but fails for MC wrappers. Still trying to figure it out myself... Related #213 ?

Tests also seem to fail. Not sure about that.

**Comment by SoniEx2** [comment]
Works locally, even after all sorts of cleans and stuff. Travis issue?

**Comment by RX14** [comment]
Travis didn't have enough ram to run 4 tests simultaneously. I have reduced the number to 1 parallel fork to reduce ram usage. This fixes the build.

**Pull request merged**
